GET http://localhost:49153/api/v1/tasks

###
GET http://localhost:49153/api/v1/tasks/find-all-task-open-by-user/15

###
GET http://localhost:49153/api/v1/tasks/find-all-task-done-by-user/12

###
GET http://localhost:49153/api/v1/tasks/17

###
GET http://localhost:49153/api/v1/tasks/find-all-tasks-by-user/15

###
POST http://localhost:49153/api/v1/tasks
Content-Type: application/json

# {
#   "description": "go to church",
#   "status": "OPEN",
#   "userId": 10
# }

{
  "description": "clean the room",
  "status": "OPEN",
  "userId": 11
}

###
POST http://localhost:49153/api/v1/tasks/15
Content-Type: application/json

{
  "description": "go to church",
  "status": "OPEN"
}

# {
#   "description": "read the bible",
#   "status": "OPEN"
# }

# {
#   "description": "bathing",
#   "status": "DONE"
# }

###
PATCH http://localhost:49153/api/v1/tasks/18
Content-Type: application/json

{
  "status": "DONE"
}

# {
#   "description": "go to party",
#   "role": "OPEN"
# }

# {
#   "status": "DONE"
# }

####
PATCH http://localhost:49153/api/v1/tasks/update-task-done/16

###
DELETE http://localhost:49153/api/v1/tasks/20


### Users
GET http://localhost:49153/api/v1/users

###
GET http://localhost:49153/api/v1/users/email/tony@ibm.com

###
GET http://localhost:49153/api/v1/users/username/brucewayne

###
POST http://localhost:49153/api/v1/users
Content-Type: application/json

# {
#   "username": "tonystark",
#   "password": "tony123",
#   "email": "tony@ibm.com"
# }

{
  "username": "brucebanner",
  "password": "bruce123",
  "email": "bruce@ibm.com"
}

# {
#   "username": "johndoe",
#   "password": "password",
#   "email": "john@ibm.com"
# }

###
DELETE http://localhost:49153/api/v1/users/3


### Auth
POST http://localhost:49153/api/v1/auth/login
Content-Type: application/json

{
  "email": "tony@ibm.com",
  "password": "tony123"
}

###
POST http://localhost:49153/api/v1/auth/register
Content-Type: application/json

{
  "username": "brucewayne",
  "email": "bruce@ibm.com",
  "password": "bruce123"
}

# {
#   "username": "tonystark",
#   "email": "tony@ibm.com",
#   "password": "tony123"
# }

# {
#   "username": "steverogers",
#   "email": "steve@ibm.com",
#   "password": "steve123"
# }

###
GET http://localhost:49153/api/v1/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbnlAaWJtLmNvbSIsInN1YiI6MTYsImlhdCI6MTcwODQ1MDA4NSwiZXhwIjoxNzA4NDUwMTQ1fQ.Ac-1heJ5M0ExUXJTEOlhVlF_S8-u9TG4U0QzOxCQdX4
